name: pimiopilot

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16-oss
    # platform: linux/arm64/v8
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TIMESCALEDB_TELEMETRY=off
    ports:
      - "5432:5432"
    volumes:
      - tsdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $${POSTGRES_DB:-marketdata}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    environment:
      - TZ=Asia/Taipei
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=marketdata
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONPATH=/app/src
      - TICKER=2330.TW
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: python -m pimiopilot_data.cli run --config examples/job.yaml
    restart: on-failure

  query:
    profiles: ["query"]
    build: .
    entrypoint: python -m pimiopilot_data.cli query
    environment:
      - DB_HOST=timescaledb
      - DB_NAME=marketdata
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - PYTHONPATH=/app/src
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    # default config; can be overridden at run-time
    command: --config examples/query.yaml
    restart: "no"

volumes:
  tsdata:
